services:
  api:
    command: ["api", "--reload"]
    volumes:
      - ./src:/app/src
      - blobs:/var/lib/legalbot/blobs

  worker:
    command: ["worker-watch"]
    volumes:
      - ./src:/app/src
      - ./docker:/app/docker
      - blobs:/var/lib/legalbot/blobs

  beat:
    command: ["beat-watch"]
    volumes:
      - ./src:/app/src
      - ./docker:/app/docker
